<?php

class Tabouret
{
    protected $h;
    protected $quality; //low medium high

    public function __construct($h, $quality)
    {
        $this->h = $h;
        $this->quality = $quality;
    }

    public function amountOfWood()
    {
        if ($this->quality == "low"){
            $q = 4*$this->h+12;
        }
        else{
            $q = 5*$this->h+14;
        }
        return $q;
    }

    public function price()
    {
        $d = $this->amountOfWood();
        $price = 0;
        if ($this->quality == "low"){
            $price = $d*2;
        }
        elseif ($this->quality == "medium"){
            $price = $d*3;
        }
        elseif ($this->quality == "high"){
            $price = $d*4;
        }
        return $price;
    }

    public function info()
    {
        return "H: {$this->h}, Quality: {$this->quality}, Wood amount: {$this->amountOfWood()}, Price: {$this->price()}";
    }
}

class Chair extends Tabouret
{
    protected $bh;

    public function __construct($h, $quality, $bh)
    {
        parent::__construct($h, $quality);
        $this->bh = $bh;
    }

    public function amountOfWood()
    {
        return parent::amountOfWood()+2*$this->bh+5; // TODO: Change the autogenerated stub
    }
}
$h = readline("Input height: ");
$quality = readline("Input quality(low/medium/high): ");
$bh = readline("Input back_height: ");
$t = new Tabouret($h,$quality);
$ch = new Chair($h,$quality,$bh);
echo "\n====================================================\n";
echo "Tabouret INFO";
echo $t->info();
echo "\n====================================================\n";
echo "Chair INFO";
echo $ch->info();
echo "\n====================================================\n";
